name: Laravel

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: PHP Linter
        uses: michaelw90/PHP-Lint@master
      - name: Security checker
        uses: symfonycorp/security-checker-action@v2
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      # - name: Create Database
      #   run: |
      #     mkdir -p database
      #     touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: pqsql
          DATABASE_URL: postgres://ajwefdfyzacqzb:469d7f67a624186c7679cd69661f929e547ab4c4502c33f983fb526d44d6ab86@ec2-46-137-124-19.eu-west-1.compute.amazonaws.com:5432/d3e35a9slpopgj
          DB_HOST: ec2-46-137-124-19.eu-west-1.compute.amazonaws.com
          DB_DATABASE: d3e35a9slpopgj
          DB_USERNAME: ajwefdfyzacqzb
          DB_PASSWORD: 469d7f67a624186c7679cd69661f929e547ab4c4502c33f983fb526d44d6ab86
        run: vendor/bin/phpunit
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
